import './_style/globals.css';
// eslint-disable-next-line import/no-unresolved
import { GeistSans } from "geist/font/sans";
import Header from './_components/organisms/Header';
import type {
  Metadata, Viewport 
} from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { ReactNode } from 'react';
import { ThemeProvider } from '../context/ThemeProvider';
import {
  getLocale, getMessages 
} from 'next-intl/server';
import { AuthProvider } from '@/context/AuthProvider';
import { Toaster } from './_components/shadcn/sonner';
import { Footer } from './_components/organisms/Footer';
import Container from './_components/layouts/Container';
import { TooltipProvider } from './_components/shadcn/tooltip';

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: 'white' },
    { media: '(prefers-color-scheme: dark)', color: 'black' },
  ]
}

export const metadata: Metadata = {
  title: {
    template: '%s | About You',
    default: 'About You',
  },
  description: 'Generated by create next app',
  generator: 'Next.js',
  applicationName: 'About You',
  referrer: 'origin-when-cross-origin',
  keywords: ['Next.js', 'React', 'JavaScript'],
  creator: 'Maela Cudini',
  metadataBase: new URL('https://addwebsite.com'),
  manifest: 'https://nextjs.org/manifest.json',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: '/',
    languages: {
      'en-US': '/en-US',
      'it-IT': '/it-IT',
    },
  },
  openGraph: {
    title: 'About You',
    description: 'The React Framework for the Web',
    url: 'https://addwebsite.com',
    siteName: 'About You',
    images: [
      {
        url: 'https://addwebsite.com/og.png',
        width: 1800,
        height: 1600,
        alt: 'My custom alt',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'About You',
    description: 'The React Framework for the Web',
    siteId: '',
    creator: '@aboutyou',
    creatorId: '',
    images: ['https://addwebsite.com/og.png'],
  },
  icons: {
    icon: '/icon.png',
    shortcut: '/shortcut-icon.png',
    apple: '/apple-icon.png',
  },
  robots: {
    index: false,
    follow: false,
    nocache: false,
    googleBot: {
      index: false,
      follow: false,
    },
  },
};

export default async function RootLayout({ children, }: Readonly<{
  children: ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning={true}>
      <body
        className={`${GeistSans.className} antialiased`} suppressHydrationWarning={true}
        id='body'
      >
        <AuthProvider>
          <NextIntlClientProvider messages={messages}>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <TooltipProvider>
                <Container>
                  <Header />
                  {children}
                  <Toaster />
                  <Footer />
                </Container>
              </TooltipProvider>
            </ThemeProvider>
          </NextIntlClientProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
