import './_style/globals.css';
// eslint-disable-next-line import/no-unresolved
import { GeistSans } from "geist/font/sans";
import Header from './_components/organisms/Header';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { ReactNode } from 'react';
import { ThemeProvider } from '../context/ThemeProvider';
import {
  getLocale, getMessages 
} from 'next-intl/server';
import { AuthProvider } from '@/context/AuthProvider';
import { Toaster } from './_components/shadcn/sonner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children, }: Readonly<{
  children: ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning={true}>
      <body
        className={`${GeistSans.className} antialiased`} suppressHydrationWarning={true}
        id='body'
      >
        <AuthProvider>
          <NextIntlClientProvider messages={messages}>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <Header />
              {children}
              <Toaster />
            </ThemeProvider>
          </NextIntlClientProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
